/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd_ashal_tutorial;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}

//1 + 2 = 3
//Calculator
// - plus(x, y)
// - minus(x, y)
// - multiply(x, y)
// - divide(x, y)
//lhs, rhs
//lhs operator rhs
// lhs = rhs