INCLUDE_PATHS = -ID:\Users\lib\mingw_dev_lib\include\SDL2
LIBRARY_PATHS = -LD:\Users\lib\mingw_dev_lib\lib
LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2

all:
		g++ -Wall -Wextra chip8.cc -o chip8 -lSDL2
		
		//g++ -Wall -Wextra chip8.cc $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(LINKER_FLAGS) -o chip8
